### ISSUE TITLE
What kind of files are supported?

### ISSUE THREAD

**Issue by mrdong916** [NiKoTron/dart-tags#11]
Hello, what kind of files are supported? Do I need to add tag ape, flac, m4a and mp3 for these music formats

**Comment by NiKoTron** [comment]
Hi, @mrdong916 ! Currently, it supports id3v1 and id3v2 tags for reading and writing. If you were caring about file extension, you shouldn't. It is independent on the file extension. Library operates with bytes, and can be used with any source not only file.

**Comment by mrdong916** [comment]
I am very sorry, the question is a bit silly because I don’t understand this very much. Thank you very much.
