### ISSUE TITLE
Decode

### ISSUE THREAD

**Issue by HazMux** [NiKoTron/dart-tags#13]
I used EasyTag to change Artist tag to "Полина Гагарина&Егор Крид"
But the package return it like "Полинаጠ〄㌄〄䀄㠄㴄〄☄Егорᨠ䀄㠄㐄�"

**Comment by NiKoTron** [comment]
Thanx for reporting! Looks very strange. Could you clarify which version of tag do you use? And if it possible, could you share/send a file with tag.

So, anyway I'll try to reproduce.

**Comment by NiKoTron** [comment]
@MaxDeadOriginal, Yep, seems to it was a wrong utf16 encoding EasyTag saves ID3 v2.3 UTF16 by default. I've uploaded a version with a fix on pub.dev let's check this out.
Please let me know if it fixed. Or not.

**Comment by HazMux** [comment]
Yes, now is works fine, thanks !
