### ISSUE TITLE
Ram Consumption 

### ISSUE THREAD

**Issue by MarcelleBond** [NiKoTron/dart-tags#14]
This is a great library. It has a problem of using a lot of Ram tho. It seems to use up all the available ram to extract the tags and when modifying those tags writing them back does the same thing.

 
![dart_tags](https://user-images.githubusercontent.com/39581969/81693545-5b6f1800-9460-11ea-9f5f-275febcd060b.PNG)
 
I am running this on a Windows machine because I want to make it for both android and windows

**Environment**
- Platform [Windows 7 X64, 8GB ram, i7 processor ]
- Library version [v0.2.3]

**Comment by NiKoTron** [comment]
Hi, @MarcelleBond! It looks very strange. Could you provide a bit more information: 
- `$ flutter doctor -v`
- is it occurs only in debug build on windows?
- did you try to reproduce this behaviour on android? and/or in release mode?
- if it possible, can you provide examples?

**Comment by MarcelleBond** [comment]
Hi @NiKoTron sorry for the late response. 

flutter version 1.19.0-1.0.pre

No it happens on android devices to 

I had tested it on an android device as well and it also consumes a lot of ram and then crashes the app.

all I do is take your example from the https://pub.dev/packages/dart_tags#-example-tab- and pasted in my code and it the errors occurred

**Comment by NiKoTron** [comment]
Thanx! Well, I'm going to investigate this issue with brand new flutter 1.19
But in addition could you please share some data files with which this problem is reproduced. If it's possible of course.

And if it's possible which program used for tagging before? it's also can help me
Maybe this file uses some specific encodings or tags. 

So.. in other words any additional information can help, especially some exact data(mp3) files.

**Comment by MarcelleBond** [comment]
So I found something interesting. It reacts differently depending on the songs. Some consume a lot of ram and other throw RangeError's and some displace a lot of random data to the screen but don't consume a lot of ram. I'm gonna attach the mp3's I used that gave me these results 

[Dart_Tags_TestFiles.zip](https://github.com/NiKoTron/dart-tags/files/4640287/Dart_Tags_TestFiles.zip)

I don't know what program was used for tagging. all these mp3's are downloaded/found on PC like that

**Comment by MarcelleBond** [comment]
never mind about the one with the random data. it was just the album art running pass my console buffer. so the Kendrick song works perfectly and quite quick but it does add some weird characters here and there but it doesn't use consume ram like the other one

**Comment by NiKoTron** [comment]
Thanx a lot! I'll check this.

**Comment by NiKoTron** [comment]
@MarcelleBond sorry for a big delay. Could you please check the latest (0.3.0) version?

**Comment by MarcelleBond** [comment]
It's no problem. I will check it out and give you feed back as soon as possible

**Comment by NiKoTron** [comment]
Should be fixed in 0.3.1
Feel free to reopen if didn't
