### ISSUE TITLE
Picture tag is no longer being extracted

### ISSUE THREAD

**Issue by NiKoTron** [NiKoTron/dart-tags#16]
since 0.3.0
from @n3rfd message:
>picture tag is no longer being extracted and returned from calling getTagsFromByteArray()

**Comment by NiKoTron** [comment]
could be related to #19

**Comment by muarachmann** [comment]
Hi, +1 on this amazing plugin. However I still can't get pictures. I go with the code
```
 TagProcessor().getTagsFromByteArray(file.readAsBytes()).then((l) {
          print('FILE: ${file.path}');
          print(l.toString());
        });
```

This prints everything but never the attached picture

**Comment by muarachmann** [comment]
Okay update sorry, after running on  a physical device, it works. On simulator however, it wasn't working
