### ISSUE TITLE
32 bit integer frame size for USLT ??

### ISSUE THREAD

**Issue by algoshipda** [NiKoTron/dart-tags#18]
I found lyrics is mis-decoding.

With some debugging, I found the fact that USLT actually uses 32bit integer for frame size.
(what about the other frame?)

If we change USLT frame size to 32 bit integer instead of the sync safe integer, it works.

**Comment by algoshipda** [comment]
It depends on the version of id3
https://gist.github.com/wader/7016435#:~:text=whole%20id3%20tag.-,v2.,integer%20(not%20synch%20safe).

**Comment by NiKoTron** [comment]
@algoshipda Thanx for the report!

I read both specs again, and according to this docs 2.3 uses not sync safe value for size - https://id3.org/id3v2.3.0#ID3v2_frame_overview
but 2.4 sync-safe - https://id3.org/id3v2.4.0-structure (paragraph 4)

I don't know why they changed it but ok, looks like I'm going to implement it.

**Comment by NiKoTron** [comment]
I've implemented a separate size calculation for v2.3 and v2.4. 
It should be fixed in this commit - https://github.com/NiKoTron/dart-tags/commit/d637088451b3445d59ed3abcb4d048ad4a8172e6
