### ISSUE TITLE
version 1.1 and 2.3.0 returned

### ISSUE THREAD

**Issue by tomrobin-teschner** [NiKoTron/dart-tags#2]
When I read the ID3 tags from a file I get two entries, one with v1.1 and one with v2.3.0 which is fine, I can filter them so I only get those with version v2.3.0 but I was just wondering if this is safe, or if there is a better way to do this. The tag processor doesn't seem to take a constructor argument so I wonder how this could be done in a clean way.

**Comment by NiKoTron** [comment]
Hello! You could pass the second argument to the method .getTagsFromByteArray()

for example:
``` dart
.getTagsFromByteArray(%some_byte_array%, [TagType.id3v2])
```

**Comment by tomrobin-teschner** [comment]
works like a charm, thanks!
