### ISSUE TITLE
Web Support? 

### ISSUE THREAD

**Issue by rmill777** [NiKoTron/dart-tags#25]
Hello, 

I would like to be able to use this library with flutter web, but I am having trouble because this library uses files defined from dart:io and not dart:html. Dart:io is not supported in flutter web, so I am not sure why this library is labelled as working with flutter web?

**Comment by NiKoTron** [comment]
Hi! But it doesn't use a `dart:io` package and file conception as well. library operate byte arrays only. Could you please describe a problem that you've been faced up?

**Comment by rmill777** [comment]
I think I have figured it out. Unfortunately, the dart:html library does not allow for byte access from local files, but only from files hosted on the web (due to security concerns).
