### ISSUE TITLE
Example for writing APIC tags

### ISSUE THREAD

**Issue by anoorally** [NiKoTron/dart-tags#3]
Can you please provide an example how an APIC tag can be written?

**Comment by NiKoTron** [comment]
Hello! So there is alreay in the tests [test/dart_tags_test.dart](https://github.com/NiKoTron/dart-tags/blob/182440c33efa0f9ea25c578becc39fbc4a4f2af0/test/dart_tags_test.dart#L32)

**Comment by anoorally** [comment]
@NiKoTron Thank you for your reply. 
I've applied your example code but its not working. I get the following:
`Unhandled Exception: 'package:dart_tags/src/writers/id3v2.dart': Failed assertion: line 76 pos 12: 'value <= 9999': is not true.`

Each frame can be 16 MB in size as quoted below:

>  Since each frame can be 16MB and the entire tag can be 256MB
(Source: http://id3.org/ID3v2Easy)

Can you please advise how to proceed?

**Comment by NiKoTron** [comment]
So, it looks like a bug, I'm going to fix it as soon as possible. Thank you for the report.

**Comment by NiKoTron** [comment]
@anoorally I've increased the limit to 16MB. The error above shouldn't occur anymore.

**Comment by anoorally** [comment]
@NiKoTron Thanks for the fix. 
I've re-tested with the updated package. The error no longer occurs, but something is off about the image. The APIC image does not show, although the mp3 file plays (which means it is not corrupt).
Dumping the tags shows the APIC in Base64, but re-converting them to image shows blank.
Would you have any suggestions?

**Comment by NiKoTron** [comment]
Writers are currently available as an experimental feature. So.. it's could be happening at this time. Also while retesting I've found some other issues with id3v2 writer.
 
Currently, I focused to rewrite some inner logic for independent frame processing, and as a result, it should solve this problem. I guess I'll finish at the end of the week. This changes will not affect the library's API.

Thanx for using and reporting about issues.

Stay tuned.

**Comment by sriharsha-y** [comment]
Hey @NiKoTron , any update on this could not get the APIC thing working and images shows blank. Thanks for this great package.

**Comment by NiKoTron** [comment]
Hi! @anoorally @sriharsha-y  Please update and check this [test](https://github.com/NiKoTron/dart-tags/blob/16a4939f90ff54b723aab266f4819450ba209b7b/test/dart_tags_test.dart#L272). It's writing a picture to mp3 then read it and generate image file and html file with base64 encoded img tag.  Also, you could check resut.mp3 with tag readers. As a reference reader, I used MusicBrainz's [picard](https://picard.musicbrainz.org/).

**Comment by NiKoTron** [comment]
@anoorally @sriharsha-y, is it ok? could I close this issue?
